[package]
name = "personal-page"
version = "0.1.0"
edition = "2021"

[dependencies]
charming = { version = "0.4.0", features = ["wasm"] }
gloo = "0.11.0"
leptos = { version = "0.6.15", features = ["csr"] }
leptos_router = { version = "0.6.15", features = ["csr"] }
rand = "0.8.5"
serde = "1.0.213"
