[application]

# dioxus project name
name = "投资模拟"

# default platform
# you can also use `dx serve/build --platform XXX` to use other platform
# value: web | desktop
default_platform = "web"

# Web `build` & `serve` dist path
out_dir = "docs"

# resource (static) file folder
asset_dir = "assets"

# hot reload by default
hot_reload = true

[web.wasm_opt]
# The level wasm-opt should target. z is the smallest. 4 is the fastest.
level = "4"

[web.app]

# HTML title tag content
title = "投资模拟"

[web.watcher]

index_on_404 = true

watch_path = ["src", "examples"]

[bundler]
# Bundle identifier
identifier = "io.github.投资模拟"

# Bundle publisher
publisher = "投资模拟"

# Bundle icon
icon = ["icons/icon.png"]

# Bundle resources
resources = ["public/*"]

# Bundle copyright
copyright = ""

# Bundle category
category = "Utility"

# Bundle short description
short_description = "An amazing dioxus application."

# Bundle long description
long_description = """
An amazing dioxus application.
"""
